apiVersion: apps/v1
kind: Deployment
metadata:
  name: minha-implantacao
spec:
  replicas: 4
  selector:
    matchLabels:
      app: minha-aplicacao
  template:
    metadata:
      labels:
        app: minha-aplicacao
    spec:
      containers:
        - name: web
          image: nginx:latest
        - name: banco-de-dados
          image: postgres:latest
          env:
            - name: POSTGRES_PASSWORD
              value: "123"
            - name: POSTGRES_USER
              value: "minsait"
            - name: POSTGRES_DB
              value: "minsait"